spring:
  profiles.active: dev
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
    serialization:
      indent_output: true
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
#    default-property-inclusion: non_empty


unique.value.violation: "Unique constraint violation"



#spring.profiles.active=dev jest ustawiony w 'edit configurations'
